
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocCLASSleftIDENTIFICADORLLAIZQASIGNAR BOOL CLASS COMA COMDOB CORDER CORIZQ ENTERO IDENTIFICADOR INT LLADER LLAIZQ NUMERAL PARDER PARIZQ PRIVATE PROTECTED PUBLIC PUNTOCOMA RETURN STRING VOID\n    expresion   :  CLASS IDENTIFICADOR LLAIZQ\n                |  PUBLIC INT IDENTIFICADOR PUNTOCOMA\n                |  PRIVATE INT IDENTIFICADOR PUNTOCOMA\n                |  PROTECTED INT IDENTIFICADOR PUNTOCOMA\n                |  PUBLIC STRING IDENTIFICADOR PUNTOCOMA\n                |  PRIVATE STRING IDENTIFICADOR PUNTOCOMA\n                |  PROTECTED STRING IDENTIFICADOR PUNTOCOMA\n                |  PUBLIC BOOL IDENTIFICADOR PUNTOCOMA\n                |  PRIVATE BOOL IDENTIFICADOR PUNTOCOMA\n                |  PROTECTED BOOL IDENTIFICADOR PUNTOCOMA\n                |  PUBLIC VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PRIVATE VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PROTECTED VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PUBLIC INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PRIVATE INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PROTECTED INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PUBLIC STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PRIVATE STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PROTECTED STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PUBLIC BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PRIVATE BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  PROTECTED BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA\n                |  LLADER\n    '
    
_lr_action_items = {'CLASS':([0,],[2,]),'PUBLIC':([0,],[3,]),'PRIVATE':([0,],[4,]),'PROTECTED':([0,],[5,]),'LLADER':([0,],[6,]),'$end':([1,6,20,33,35,37,40,42,44,47,49,51,66,67,68,69,70,71,72,73,74,75,76,77,],[0,-23,-1,-2,-5,-8,-3,-6,-9,-4,-7,-10,-14,-17,-20,-11,-15,-18,-21,-12,-16,-19,-22,-13,]),'IDENTIFICADOR':([2,8,9,10,11,12,13,14,15,16,17,18,19,],[7,21,22,23,24,25,26,27,28,29,30,31,32,]),'INT':([3,4,5,],[8,12,16,]),'STRING':([3,4,5,],[9,13,17,]),'BOOL':([3,4,5,],[10,14,18,]),'VOID':([3,4,5,],[11,15,19,]),'LLAIZQ':([7,],[20,]),'PUNTOCOMA':([21,22,23,25,26,27,29,30,31,54,55,56,57,58,59,60,61,62,63,64,65,],[33,35,37,40,42,44,47,49,51,66,67,68,69,70,71,72,73,74,75,76,77,]),'PARIZQ':([21,22,23,24,25,26,27,28,29,30,31,32,],[34,36,38,39,41,43,45,46,48,50,52,53,]),'PARDER':([34,36,38,39,41,43,45,46,48,50,52,53,],[54,55,56,57,58,59,60,61,62,63,64,65,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> CLASS IDENTIFICADOR LLAIZQ','expresion',3,'p_class_syntax','syntacticAnalyzer.py',17),
  ('expresion -> PUBLIC INT IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',18),
  ('expresion -> PRIVATE INT IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',19),
  ('expresion -> PROTECTED INT IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',20),
  ('expresion -> PUBLIC STRING IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',21),
  ('expresion -> PRIVATE STRING IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',22),
  ('expresion -> PROTECTED STRING IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',23),
  ('expresion -> PUBLIC BOOL IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',24),
  ('expresion -> PRIVATE BOOL IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',25),
  ('expresion -> PROTECTED BOOL IDENTIFICADOR PUNTOCOMA','expresion',4,'p_class_syntax','syntacticAnalyzer.py',26),
  ('expresion -> PUBLIC VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',27),
  ('expresion -> PRIVATE VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',28),
  ('expresion -> PROTECTED VOID IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',29),
  ('expresion -> PUBLIC INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',30),
  ('expresion -> PRIVATE INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',31),
  ('expresion -> PROTECTED INT IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',32),
  ('expresion -> PUBLIC STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',33),
  ('expresion -> PRIVATE STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',34),
  ('expresion -> PROTECTED STRING IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',35),
  ('expresion -> PUBLIC BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',36),
  ('expresion -> PRIVATE BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',37),
  ('expresion -> PROTECTED BOOL IDENTIFICADOR PARIZQ PARDER PUNTOCOMA','expresion',6,'p_class_syntax','syntacticAnalyzer.py',38),
  ('expresion -> LLADER','expresion',1,'p_class_syntax','syntacticAnalyzer.py',39),
]
